# Generated by Django 5.0.4 on 2024-05-01 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('player_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_points', to='doko_api_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('game_name', models.CharField(max_length=200)),
                ('is_closed', models.BooleanField(default=False)),
                ('players', models.ManyToManyField(blank=True, related_name='games', to='doko_api_app.player')),
                ('player_points', models.ManyToManyField(blank=True, related_name='games', to='doko_api_app.playerpoints')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='doko_api_app.game')),
                ('player_points', models.ManyToManyField(blank=True, related_name='rounds', to='doko_api_app.playerpoints')),
            ],
        ),
    ]
