# Generated by Django 5.0.6 on 2024-06-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doko_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bock_round_status',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='round',
            name='bocks_parallel',
            field=models.IntegerField(default=0),
        ),
    ]
