# Generated by Django 5.0.6 on 2024-06-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doko_api_app', '0002_game_bock_round_status_round_bocks_parallel'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='bock_multiplier',
            field=models.IntegerField(default=1),
        ),
    ]
