# Generated by Django 5.0.6 on 2024-06-20 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doko_api_app', '0004_game_flag_removed_player_flag_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='was_solo_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds', to='doko_api_app.player', to_field='player_id'),
        ),
    ]
