# Generated by Django 5.0.6 on 2024-12-18 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doko_api_app', '0005_round_was_solo_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='was_pflichtsolo_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pflichtsolo_rounds', to='doko_api_app.player', to_field='player_id'),
        ),
        migrations.AlterField(
            model_name='round',
            name='was_solo_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solo_rounds', to='doko_api_app.player', to_field='player_id'),
        ),
    ]
