version: '3.8'

services:
  web:
    image: valentin123/doko-api-web:latest
    command: gunicorn doko_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - ./prod.env
    depends_on:
      - db
    networks:
      doko-api-network:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./prod.db.env
    networks:
      doko-api-network:

  nginx:
    image: valentin123/doko-api-nginx:latest
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 80
    depends_on:
      - web
    networks:
      doko-api-network:

  discord_bot:
    image: valentin123/doko-discord-bot:latest
    command: python main.py
    env_file:
      - ./prod.bot.env # get this file from the bot git repo
    networks:
        doko-api-network:
    depends_on:
      - nginx

volumes:
  postgres_data:
  static_volume:

networks:
  doko-api-network: