version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./dev.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      #- ./data/:/var/lib/postgresql/data/
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=doko

volumes:
  postgres_data: