version: '3.8'

services:
  web:
    #image: valentin123/doko-api:1.0
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn doko_api.wsgi:application --bind 0.0.0.0:8000
    #expose:
    #  - 8000
    ports:
      - 8000:8000
    env_file:
      - ./prod.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./prod.db.env

volumes:
  postgres_data: