version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./prod.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      #- ./data/:/var/lib/postgresql/data/
      - postgres_data:/var/lib/postgresql/data/
    env_file:
        - ./prod.db.env

volumes:
  postgres_data: